---
exclude_paths:
  - 'drizzle/migrations/**'
  - '**/*.sql'
  - 'scripts/*.sql'
  - 'migration*.sql'
  - 'cleanup*.sql'
  # Exclude files with false positive Codacy warnings for valid modern JavaScript syntax
  # (template literals and trailing commas are valid ES6+ syntax)
  - 'src/components/admin/RichTextEditor.tsx'
  - 'src/app/api/checkout/route.ts'
  - 'src/app/api/webhooks/clerk/route.ts'
  - 'src/app/admin/decks/[id]/page.tsx'
  - 'src/app/dashboard/domain/[id]/page.tsx'
  - 'src/app/head.tsx'
  - 'src/components/Flashcard.tsx'
  - 'src/app/dashboard/deck/[id]/page.tsx'
  - 'src/app/dashboard/class/[id]/study/page.tsx'


engines:
  # Disable SCSS-specific linters for Tailwind CSS files
  stylelint:
    exclude_paths:
      - 'src/app/globals.css'

  # Disable SQL Server-specific linters (we use PostgreSQL)
  sqlint:
    enabled: false

  # Disable ESLint9 - it can't load Next.js configs in Codacy's container
  # Local ESLint still works fine for development
  eslint:
    enabled: false

  # Disable Semgrep patterns that cause false positives
  # - styled-jsx template literals (Next.js built-in CSS-in-JS)
  # - JSON examples in code comments
  # - Non-literal filesystem paths in trusted build/migration scripts
  semgrep:
    enabled: true
    exclude_patterns:
      - 'detect-missing-template-string'
      - 'javascript.lang.security.detect-missing-template-string'
      - 'generic.secrets.security.detected-generic-secret'
      - 'javascript.lang.security.detect-non-literal-fs-filename'
      - 'javascript.lang.security.audit.path-traversal.path-join-resolve-traversal'
    exclude_paths:
      # styled-jsx is the official Next.js CSS-in-JS solution
      # These files use <style jsx>{`...`} which is correct syntax
      - 'src/app/dashboard/class/[id]/study/page.tsx'
      - 'src/app/dashboard/domain/[id]/page.tsx'
      - 'src/app/admin/decks/[id]/page.tsx'
      - 'src/app/dashboard/deck/[id]/page.tsx'

  # Disable Lizard cyclomatic complexity warnings for false positives
  # Lizard over-counts operators (??, &&, ||) as complexity points
  # See .github/instructions/codacy-cyclomatic-complexity-false-positives.md
  lizard:
    enabled: true
    exclude_paths:
      # messageContainsKeyword: flagged as 10, actually 1 (single .some() call)
      - 'src/lib/api/error-handler.ts'
      # buildDeckValues: flagged as 11, actually 1 (object creation with ?? operators)
      - 'src/app/api/admin/decks/route.ts'
      # shouldIncludeInProgressiveMode: flagged as 25, actually 3 (3 simple if statements)
      - 'src/app/api/classes/[id]/study/route.ts'


  typescript:
    enabled: true

  # Enforce medium NLOC (Number of Lines of Code) limit
  # Checks if functions exceed 50 lines of code (excluding comments)
  # 
  # Note: Codacy's PMD tool reports some false positives for cyclomatic complexity:
  # - buildDeckValues (complexity 11): Actually simple object creation with null coalescing
  # - messageContainsKeyword (complexity 10): Simple .some() call, 2 lines of code
  # - shouldIncludeInProgressiveMode (complexity 23): 3 simple if statements, 17 lines
  # These are flagged due to how PMD counts operators, not actual code complexity
  pmd:
    enabled: true
    exclude_patterns:
      - 'test/**'
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
      # Exclude lock files and generated files
      - 'pnpm-lock.yaml'
      - 'package-lock.json'
      - 'yarn.lock'
      # Exclude legal/policy pages from 50-line NLOC limit
      # These should remain as single coherent documents for legal review
      - 'src/app/terms-and-conditions/**'
      - 'src/app/privacy-policy/**'
      # Exclude pricing page (content-heavy marketing page)
      - 'src/app/pricing/**'
      # Exclude E2E test setup files
      - 'e2e/**'
    patterns:
      - category: CodeStyle
        parameters:
          NCSS_METHOD_MINIMUM: 50

# Exclude patterns that should not be analyzed
exclude_patterns:
  - '**/*.sql'
  - 'drizzle/migrations/**'
  - 'node_modules/**'
  - '.next/**'
  - 'dist/**'
  - 'build/**'
