---
exclude_paths:
  - 'drizzle/migrations/**'
  - '**/*.sql'
  - 'scripts/*.sql'
  - 'migration*.sql'
  - 'cleanup*.sql'
  # Exclude files with false positive Codacy warnings for valid modern JavaScript syntax
  # (template literals and trailing commas are valid ES6+ syntax)
  - 'verify-schema.js'
  - 'drop-test-status.js'
  - 'cleanup-orphaned-enums.js'
  - 'check-db-state.js'
  - 'cleanup-xata.js'
  - 'investigate-enums.js'
  - 'fix-database.js'
  - 'deep-cleanup.js'
  - 'run-xata-fix.js'
  - 'fix-migrations.js'
  - 'check-test-status.js'
  - 'fix-test-status.js'
  - 'final-cleanup.js'
  - 'force-cleanup.js'
  - 'src/components/admin/RichTextEditor.tsx'
  - 'src/app/api/checkout/route.ts'
  - 'src/app/api/webhooks/clerk/route.ts'
  - 'src/app/admin/decks/[id]/page.tsx'
  - 'src/app/dashboard/domain/[id]/page.tsx'
  - 'src/app/head.tsx'
  - 'src/components/Flashcard.tsx'
  - 'src/app/dashboard/deck/[id]/page.tsx'
  - 'src/app/dashboard/class/[id]/study/page.tsx'


engines:
  # Disable SCSS-specific linters for Tailwind CSS files
  stylelint:
    exclude_paths:
      - 'src/app/globals.css'

  # Disable SQL Server-specific linters (we use PostgreSQL)
  sqlint:
    enabled: false

  # Disable ESLint9 - it can't load Next.js configs in Codacy's container
  # Local ESLint still works fine for development
  eslint:
    enabled: false

  # Disable Semgrep pattern that causes false positives with styled-jsx and JSON examples
  semgrep:
    enabled: true
    exclude_patterns:
      - 'detect-missing-template-string'

  typescript:
    enabled: true

# Exclude patterns that should not be analyzed
exclude_patterns:
  - '**/*.sql'
  - 'drizzle/migrations/**'
  - 'node_modules/**'
  - '.next/**'
  - 'dist/**'
  - 'build/**'
